import type { ReplyItem } from "./data";

export const scaleCategories = [
  { slug: "interviews", name: "Interviews & Careers", icon: "UserCheck", description: "Interview scheduling, follow-ups, offers, rejections, negotiations, and career conversations." },
  { slug: "hr-workplace", name: "HR & Workplace", icon: "Building2", description: "Clear replies for leave, performance, policies, conflict, onboarding, and workplace requests." },
  { slug: "freelancing", name: "Freelancing", icon: "Laptop", description: "Practical replies for proposals, scope, revisions, payments, deadlines, and client management." },
  { slug: "finance", name: "Banking & Finance", icon: "Landmark", description: "Professional messages for payments, cards, transfers, invoices, claims, and account questions." },
  { slug: "networking", name: "Networking", icon: "Network", description: "Confident replies for introductions, referrals, LinkedIn messages, events, and professional connections." },
] as const;

type Topic = { slug: string; title: string; category: string; categorySlug: string; keywords: string[]; context: string };

const topics: Topic[] = [
  ["confirm-second-interview","Confirm a Second Interview","Interviews & Careers","interviews",["second interview","confirmation"],"confirm the next interview and show continued interest"],
  ["request-interview-reschedule","Request to Reschedule an Interview","Interviews & Careers","interviews",["interview reschedule"],"ask for a different interview time without sounding unreliable"],
  ["interview-thank-you-email","Send an Interview Thank-You Email","Interviews & Careers","interviews",["interview thank you"],"thank the interviewer and reinforce your fit"],
  ["follow-up-after-no-interview-response","Follow Up After No Interview Response","Interviews & Careers","interviews",["interview follow up","no response"],"check on the hiring process politely"],
  ["reply-to-interview-rejection","Reply to an Interview Rejection","Interviews & Careers","interviews",["job rejection"],"respond professionally and preserve the relationship"],
  ["ask-for-interview-feedback","Ask for Feedback After an Interview","Interviews & Careers","interviews",["interview feedback"],"request constructive feedback respectfully"],
  ["accept-internship-offer","Accept an Internship Offer","Interviews & Careers","interviews",["internship offer"],"accept an internship and confirm next steps"],
  ["decline-internship-offer","Decline an Internship Offer","Interviews & Careers","interviews",["decline internship"],"decline an internship while remaining appreciative"],
  ["negotiate-start-date","Negotiate a Job Start Date","Interviews & Careers","interviews",["start date negotiation"],"request a practical start date"],
  ["ask-about-remote-work","Ask About Remote Work During Hiring","Interviews & Careers","interviews",["remote work","hiring"],"clarify workplace flexibility"],
  ["reply-to-reference-request","Reply to a Reference Request","Interviews & Careers","interviews",["reference request"],"provide or discuss professional references"],
  ["thank-recruiter-for-update","Thank a Recruiter for an Update","Interviews & Careers","interviews",["recruiter update"],"acknowledge a hiring update"],
  ["withdraw-job-application","Withdraw a Job Application","Interviews & Careers","interviews",["withdraw application"],"leave a hiring process professionally"],
  ["reply-to-background-check","Reply to a Background Check Request","Interviews & Careers","interviews",["background check"],"confirm background-check requirements"],
  ["ask-about-job-benefits","Ask About Benefits Before Accepting","Interviews & Careers","interviews",["job benefits"],"clarify benefits before deciding"],
  ["request-annual-leave","Request Annual Leave","HR & Workplace","hr-workplace",["annual leave","vacation request"],"request time off with clear dates and coverage"],
  ["reply-to-leave-approval","Reply to Leave Approval","HR & Workplace","hr-workplace",["leave approved"],"acknowledge approved leave"],
  ["reply-to-leave-denial","Reply to Leave Denial","HR & Workplace","hr-workplace",["leave denied"],"respond constructively to a denied request"],
  ["request-sick-leave","Request Sick Leave","HR & Workplace","hr-workplace",["sick leave"],"notify a manager about illness professionally"],
  ["reply-to-performance-review","Reply to a Performance Review","HR & Workplace","hr-workplace",["performance review"],"acknowledge feedback and define next steps"],
  ["ask-for-raise-meeting","Ask for a Salary Review Meeting","HR & Workplace","hr-workplace",["salary review","raise"],"request a compensation discussion"],
  ["reply-to-promotion-announcement","Reply to a Promotion Announcement","HR & Workplace","hr-workplace",["promotion announcement"],"thank colleagues and leaders for recognition"],
  ["report-workplace-conflict","Report a Workplace Conflict","HR & Workplace","hr-workplace",["workplace conflict"],"raise a concern factually and calmly"],
  ["reply-to-hr-investigation","Reply to an HR Investigation Request","HR & Workplace","hr-workplace",["HR investigation"],"cooperate while asking for clear process details"],
  ["request-flexible-hours","Request Flexible Working Hours","HR & Workplace","hr-workplace",["flexible hours"],"propose a workable flexible schedule"],
  ["reply-to-policy-update","Acknowledge a Workplace Policy Update","HR & Workplace","hr-workplace",["policy update"],"confirm understanding of a new policy"],
  ["welcome-new-employee","Welcome a New Employee","HR & Workplace","hr-workplace",["new employee","welcome"],"help a new colleague feel included"],
  ["reply-to-onboarding-email","Reply to an Onboarding Email","HR & Workplace","hr-workplace",["onboarding"],"confirm onboarding tasks and questions"],
  ["request-employment-letter","Request an Employment Verification Letter","HR & Workplace","hr-workplace",["employment letter"],"ask HR for formal employment confirmation"],
  ["give-two-weeks-notice","Give Two Weeks' Notice","HR & Workplace","hr-workplace",["resignation notice"],"resign professionally and support handover"],
  ["reply-to-exit-interview","Reply to an Exit Interview Invitation","HR & Workplace","hr-workplace",["exit interview"],"confirm or reschedule an exit interview"],
  ["reply-to-project-delay","Reply to a Project Delay","Freelancing","freelancing",["project delay","client"],"explain a delay and give a recovery plan"],
  ["request-project-deposit","Request a Project Deposit","Freelancing","freelancing",["deposit","freelance"],"request the agreed upfront payment"],
  ["reply-to-scope-creep","Reply to Scope Creep","Freelancing","freelancing",["scope creep"],"protect project scope without damaging rapport"],
  ["reply-to-revision-request","Reply to a Revision Request","Freelancing","freelancing",["revision request"],"confirm revisions and boundaries"],
  ["decline-unpaid-work","Decline Unpaid Work","Freelancing","freelancing",["unpaid work"],"decline speculative work professionally"],
  ["send-freelance-proposal","Send a Freelance Proposal","Freelancing","freelancing",["freelance proposal"],"present scope, value, timeline, and next step"],
  ["follow-up-on-proposal","Follow Up on a Freelance Proposal","Freelancing","freelancing",["proposal follow up"],"check whether a client is ready to proceed"],
  ["ask-client-for-assets","Ask a Client for Missing Assets","Freelancing","freelancing",["client assets"],"request files needed to continue work"],
  ["reply-to-rush-request","Reply to an Urgent Rush Request","Freelancing","freelancing",["rush request"],"set expectations for urgent work"],
  ["raise-freelance-rates","Tell a Client Your Rates Are Increasing","Freelancing","freelancing",["rate increase"],"communicate a rate change clearly"],
  ["end-client-contract","End a Freelance Client Contract","Freelancing","freelancing",["end client contract"],"close a difficult engagement professionally"],
  ["request-client-testimonial","Request a Client Testimonial","Freelancing","freelancing",["client testimonial"],"ask for concise feedback after delivery"],
  ["confirm-project-completion","Confirm Project Completion","Freelancing","freelancing",["project completion"],"summarize delivery and final steps"],
  ["reply-to-late-client-feedback","Reply to Late Client Feedback","Freelancing","freelancing",["late feedback"],"reset timeline after delayed feedback"],
  ["reply-to-budget-too-low","Reply When a Client's Budget Is Too Low","Freelancing","freelancing",["low budget"],"decline or reduce scope respectfully"],
  ["reply-to-card-decline","Reply About a Declined Card Transaction","Banking & Finance","finance",["card declined"],"ask a bank or merchant to investigate"],
  ["report-unauthorized-transaction","Report an Unauthorized Transaction","Banking & Finance","finance",["unauthorized transaction"],"report suspicious account activity quickly"],
  ["follow-up-bank-transfer","Follow Up on a Bank Transfer","Banking & Finance","finance",["bank transfer"],"trace a delayed transfer"],
  ["request-bank-statement","Request a Bank Statement","Banking & Finance","finance",["bank statement"],"request account records for a period"],
  ["reply-to-loan-approval","Reply to a Loan Approval","Banking & Finance","finance",["loan approval"],"acknowledge approval and ask about terms"],
  ["reply-to-loan-rejection","Reply to a Loan Rejection","Banking & Finance","finance",["loan rejected"],"request reasons and alternatives"],
  ["dispute-bank-fee","Dispute a Bank Fee","Banking & Finance","finance",["bank fee"],"request review of an unexpected fee"],
  ["request-payment-plan","Request a Payment Plan","Banking & Finance","finance",["payment plan"],"propose manageable repayment terms"],
  ["confirm-payment-received","Confirm Payment Received","Banking & Finance","finance",["payment received"],"acknowledge receipt and close the loop"],
  ["reply-to-invoice-query","Reply to an Invoice Query","Banking & Finance","finance",["invoice query"],"clarify invoice details"],
  ["request-refund-status","Request a Refund Status Update","Banking & Finance","finance",["refund status"],"ask for a clear refund timeline"],
  ["reply-to-insurance-claim","Reply to an Insurance Claim Update","Banking & Finance","finance",["insurance claim"],"acknowledge and clarify claim progress"],
  ["ask-for-receipt","Ask for a Payment Receipt","Banking & Finance","finance",["payment receipt"],"request proof of payment"],
  ["reply-to-credit-limit-change","Reply to a Credit Limit Change","Banking & Finance","finance",["credit limit"],"accept or question a limit change"],
  ["close-bank-account","Request to Close a Bank Account","Banking & Finance","finance",["close account"],"request account closure and confirmation"],
  ["accept-linkedin-connection","Accept a LinkedIn Connection","Networking","networking",["LinkedIn connection"],"start a useful professional conversation"],
  ["reply-to-networking-introduction","Reply to a Professional Introduction","Networking","networking",["professional introduction"],"thank the introducer and greet the new contact"],
  ["request-informational-interview","Request an Informational Interview","Networking","networking",["informational interview"],"ask for a short career conversation"],
  ["follow-up-after-networking-event","Follow Up After a Networking Event","Networking","networking",["networking follow up"],"continue a conversation after an event"],
  ["reply-to-referral-offer","Reply to an Offer of a Referral","Networking","networking",["referral offer"],"accept help and provide useful details"],
  ["ask-for-professional-referral","Ask for a Professional Referral","Networking","networking",["ask for referral"],"request a referral without pressure"],
  ["decline-networking-meeting","Decline a Networking Meeting","Networking","networking",["decline networking"],"decline kindly while preserving the connection"],
  ["thank-event-speaker","Thank a Conference Speaker","Networking","networking",["conference speaker"],"send specific appreciation after a talk"],
  ["reply-to-mentor-message","Reply to a Mentor","Networking","networking",["mentor"],"acknowledge guidance and share progress"],
  ["ask-mentor-for-advice","Ask a Mentor for Advice","Networking","networking",["mentor advice"],"ask a focused, respectful question"],
  ["introduce-two-professionals","Introduce Two Professional Contacts","Networking","networking",["professional introduction"],"make a clear, permission-based introduction"],
  ["reply-to-collaboration-inquiry","Reply to a Collaboration Inquiry","Networking","networking",["collaboration"],"explore fit, scope, and next steps"],
  ["decline-collaboration","Decline a Collaboration","Networking","networking",["decline collaboration"],"say no while keeping goodwill"],
  ["request-event-details","Request Details About a Business Event","Networking","networking",["business event"],"clarify agenda, audience, and logistics"],
  ["thank-someone-for-referral","Thank Someone for a Referral","Networking","networking",["thank referral"],"show appreciation and share a brief update"],
] .map(([slug,title,category,categorySlug,keywords,context]) => ({slug,title,category,categorySlug,keywords,context})) as Topic[];


const additionalTopics = [
  ["reply-to-order-cancellation","Reply to an Order Cancellation","Customer Service","customer-service",["order cancellation"],"confirm cancellation, refund, and next steps"],
  ["reply-to-damaged-item","Reply to a Damaged Item Complaint","Customer Service","customer-service",["damaged item"],"apologize and arrange replacement or refund"],
  ["reply-to-wrong-item","Reply to a Wrong Item Complaint","Customer Service","customer-service",["wrong item"],"correct the order quickly"],
  ["reply-to-delivery-delay","Reply to a Delivery Delay Complaint","Customer Service","customer-service",["delivery delay"],"explain the delay and provide a realistic update"],
  ["reply-to-service-outage","Reply to a Service Outage Complaint","Customer Service","customer-service",["service outage"],"acknowledge disruption and share restoration updates"],
  ["reply-to-billing-error","Reply to a Billing Error","Customer Service","customer-service",["billing error"],"investigate and correct a billing problem"],
  ["reply-to-account-locked","Reply to a Locked Account Request","Customer Service","customer-service",["account locked"],"help restore account access securely"],
  ["reply-to-subscription-cancellation","Reply to a Subscription Cancellation","Customer Service","customer-service",["subscription cancellation"],"confirm cancellation and final billing details"],
  ["reply-to-product-return","Reply to a Product Return Request","Customer Service","customer-service",["product return"],"explain return eligibility and instructions"],
  ["reply-to-negative-review","Reply to a Negative Review","Customer Service","customer-service",["negative review"],"respond publicly with empathy and a path to resolution"],
  ["reply-to-positive-review","Reply to a Positive Review","Customer Service","customer-service",["positive review"],"thank the customer and reinforce goodwill"],
  ["reply-to-feature-request","Reply to a Customer Feature Request","Customer Service","customer-service",["feature request"],"acknowledge feedback without making false promises"],
  ["reply-to-discount-request","Reply to a Discount Request","Sales & Clients","sales",["discount request"],"protect value while exploring options"],
  ["reply-to-price-objection","Reply to a Price Objection","Sales & Clients","sales",["price objection"],"explain value and clarify priorities"],
  ["reply-to-sales-inquiry","Reply to a Sales Inquiry","Sales & Clients","sales",["sales inquiry"],"qualify the need and propose a next step"],
  ["reply-to-demo-request","Reply to a Demo Request","Sales & Clients","sales",["demo request"],"schedule a relevant product demonstration"],
  ["reply-to-proposal-acceptance","Reply to a Proposal Acceptance","Sales & Clients","sales",["proposal accepted"],"confirm acceptance and launch next steps"],
  ["reply-to-proposal-rejection","Reply to a Proposal Rejection","Sales & Clients","sales",["proposal rejected"],"respond professionally and seek useful feedback"],
  ["reply-to-contract-question","Reply to a Contract Question","Sales & Clients","sales",["contract question"],"clarify terms without creating ambiguity"],
  ["reply-to-renewal-reminder","Reply to a Renewal Reminder","Sales & Clients","sales",["renewal reminder"],"confirm, question, or decline a renewal"],
  ["reply-to-client-introduction","Reply to a New Client Introduction","Sales & Clients","sales",["new client"],"welcome a new client and establish next steps"],
  ["reply-to-client-compliment","Reply to a Client Compliment","Sales & Clients","sales",["client compliment"],"accept praise and reinforce the partnership"],
  ["reply-to-school-admission-offer","Reply to a School Admission Offer","Education","education",["admission offer"],"accept or ask questions about admission"],
  ["reply-to-scholarship-award","Reply to a Scholarship Award","Education","education",["scholarship award"],"express gratitude and confirm requirements"],
  ["reply-to-scholarship-rejection","Reply to a Scholarship Rejection","Education","education",["scholarship rejection"],"respond graciously and ask about future options"],
  ["request-assignment-extension","Request an Assignment Extension","Education","education",["assignment extension"],"ask for additional time responsibly"],
  ["reply-to-late-assignment","Reply About a Late Assignment","Education","education",["late assignment"],"acknowledge delay and propose completion"],
  ["ask-professor-for-meeting","Ask a Professor for a Meeting","Education","education",["professor meeting"],"request focused academic guidance"],
  ["reply-to-teacher-feedback","Reply to Teacher Feedback","Education","education",["teacher feedback"],"acknowledge feedback and improvement steps"],
  ["reply-to-parent-complaint","Reply to a Parent Complaint","Education","education",["parent complaint"],"address a concern calmly and factually"],
  ["request-recommendation-letter","Request a Recommendation Letter","Education","education",["recommendation letter"],"ask early and provide useful context"],
  ["thank-teacher-message","Thank a Teacher","Education","education",["thank teacher"],"show specific appreciation for support"],
  ["reply-to-graduation-wishes","Reply to Graduation Wishes","Education","education",["graduation wishes"],"thank others for celebrating your achievement"],
  ["reply-to-exam-reschedule","Reply to an Exam Reschedule Notice","Education","education",["exam reschedule"],"confirm the new exam arrangement"],
  ["reply-to-hotel-booking-confirmation","Reply to a Hotel Booking Confirmation","Travel & Hospitality","travel",["hotel booking"],"confirm dates, guests, and special requests"],
  ["request-hotel-early-checkin","Request Early Hotel Check-In","Travel & Hospitality","travel",["early check-in"],"ask about early arrival options"],
  ["request-hotel-late-checkout","Request Late Hotel Check-Out","Travel & Hospitality","travel",["late checkout"],"ask about availability and fees"],
  ["reply-to-flight-cancellation","Reply to a Flight Cancellation","Travel & Hospitality","travel",["flight cancellation"],"request rebooking or refund options"],
  ["reply-to-flight-delay","Reply to a Flight Delay","Travel & Hospitality","travel",["flight delay"],"ask for updated timing and assistance"],
  ["reply-to-lost-luggage","Reply About Lost Luggage","Travel & Hospitality","travel",["lost luggage"],"track missing baggage and claim essentials"],
  ["reply-to-airbnb-host","Reply to an Airbnb Host","Travel & Hospitality","travel",["Airbnb host"],"confirm stay details and house requirements"],
  ["reply-to-guest-review","Reply to a Guest Review","Travel & Hospitality","travel",["guest review"],"thank a guest or address feedback professionally"],
  ["request-booking-change","Request a Travel Booking Change","Travel & Hospitality","travel",["booking change"],"change dates or guest details"],
  ["reply-to-visa-document-request","Reply to a Visa Document Request","Travel & Hospitality","travel",["visa documents"],"provide or clarify requested travel documents"],
  ["reply-to-appointment-reminder","Reply to a Medical Appointment Reminder","Healthcare","healthcare",["appointment reminder"],"confirm or change an appointment"],
  ["request-medical-records","Request Medical Records","Healthcare","healthcare",["medical records"],"request records through a secure process"],
  ["reply-to-doctor-follow-up","Reply to a Doctor Follow-Up Message","Healthcare","healthcare",["doctor follow up"],"acknowledge guidance and ask relevant questions"],
  ["request-prescription-refill","Request a Prescription Refill","Healthcare","healthcare",["prescription refill"],"request medication renewal safely"],
  ["reply-to-insurance-denial","Reply to a Health Insurance Denial","Healthcare","healthcare",["insurance denial"],"ask for reasons and appeal steps"],
  ["cancel-medical-appointment","Cancel a Medical Appointment","Healthcare","healthcare",["cancel appointment"],"cancel with adequate notice"],
  ["reply-to-specialist-referral","Reply to a Specialist Referral","Healthcare","healthcare",["specialist referral"],"confirm referral details and scheduling"],
  ["ask-about-test-preparation","Ask About Medical Test Preparation","Healthcare","healthcare",["test preparation"],"clarify fasting, medication, and arrival instructions"],
  ["reply-to-friend-apology","Reply to a Friend's Apology","Relationships","relationships",["friend apology"],"accept, set boundaries, or request time"],
  ["reply-to-partner-apology","Reply to a Partner's Apology","Relationships","relationships",["partner apology"],"respond honestly while protecting the relationship"],
  ["set-personal-boundary","Set a Personal Boundary","Relationships","relationships",["personal boundary"],"state a limit clearly and respectfully"],
  ["decline-personal-invitation","Decline a Personal Invitation","Relationships","relationships",["decline invitation"],"say no warmly without overexplaining"],
  ["reply-to-missed-call","Reply to a Missed Call","Social","social",["missed call"],"acknowledge the call and arrange a better time"],
  ["reply-to-long-time-no-see","Reply to 'Long Time No See'","Social","social",["long time no see"],"restart a conversation naturally"],
  ["reply-to-get-well-wishes","Reply to Get-Well Wishes","Thank You","thank-you",["get well wishes"],"thank someone for care and support"],
  ["reply-to-wedding-wishes","Reply to Wedding Wishes","Thank You","thank-you",["wedding wishes"],"thank others for warm congratulations"],
  ["reply-to-condolence-message","Reply to a Condolence Message","Thank You","thank-you",["condolence"],"acknowledge sympathy during a difficult time"],
  ["thank-someone-for-gift","Thank Someone for a Gift","Thank You","thank-you",["thank gift"],"show genuine appreciation for a thoughtful gift"],
  ["accept-business-invitation","Accept a Business Invitation","Invitations","invitations",["business invitation"],"confirm attendance and relevant details"],
  ["decline-business-invitation","Decline a Business Invitation","Invitations","invitations",["decline business invitation"],"decline professionally and preserve goodwill"],
  ["reply-to-wedding-invitation","Reply to a Wedding Invitation","Invitations","invitations",["wedding invitation"],"accept or decline with warmth"],
  ["reply-to-event-reminder","Reply to an Event Reminder","Invitations","invitations",["event reminder"],"confirm attendance or update the organizer"],
  ["request-invitation-details","Request More Invitation Details","Invitations","invitations",["invitation details"],"clarify time, location, dress, or guests"],
  ["reply-to-calendar-invite","Reply to a Calendar Invitation","Work","work",["calendar invite"],"accept, decline, or request context for a meeting"],
  ["reply-to-team-announcement","Reply to a Team Announcement","Work","work",["team announcement"],"acknowledge an internal update professionally"],
  ["reply-to-deadline-reminder","Reply to a Deadline Reminder","Work","work",["deadline reminder"],"confirm progress and delivery timing"],
  ["request-work-from-home","Request to Work From Home","HR & Workplace","hr-workplace",["work from home"],"request remote work for a specific period"],
  ["reply-to-overtime-request","Reply to an Overtime Request","HR & Workplace","hr-workplace",["overtime request"],"accept, decline, or clarify additional hours"],
  ["reply-to-client-referral","Reply to a Client Referral","Sales & Clients","sales",["client referral"],"thank the referrer and welcome the prospect"],
  ["reply-to-free-trial-request","Reply to a Free Trial Request","Sales & Clients","sales",["free trial"],"explain trial access and next steps"],
  ["reply-to-partnership-proposal","Reply to a Partnership Proposal","Sales & Clients","sales",["partnership proposal"],"assess fit and suggest a discovery call"],
  ["reply-to-course-enrollment","Reply to a Course Enrollment Confirmation","Education","education",["course enrollment"],"confirm enrollment and preparation steps"],
  ["reply-to-class-cancellation","Reply to a Class Cancellation","Education","education",["class cancellation"],"acknowledge the cancellation and ask about alternatives"],
  ["reply-to-hotel-complaint","Reply to a Hotel Complaint","Travel & Hospitality","travel",["hotel complaint"],"address a guest concern and offer resolution"],
  ["reply-to-airline-compensation","Request Airline Delay Compensation","Travel & Hospitality","travel",["airline compensation"],"request eligible compensation with supporting details"],
  ["reply-to-lab-appointment","Reply to a Laboratory Appointment","Healthcare","healthcare",["lab appointment"],"confirm timing and test preparation"],
  ["reply-to-therapy-appointment","Reply to a Therapy Appointment Confirmation","Healthcare","healthcare",["therapy appointment"],"confirm or reschedule a therapy session"],
  ["reply-to-family-invitation","Reply to a Family Invitation","Relationships","relationships",["family invitation"],"accept or decline while keeping the tone warm"],
].map(([slug,title,category,categorySlug,keywords,context]) => ({slug,title,category,categorySlug,keywords,context})) as Topic[];

function variantsFor(topic: Topic) {
  const subject = topic.title.replace(/^(Reply to|Reply About|Request to|Request|Ask for|Ask About|Ask|Confirm|Send|Follow Up on|Follow Up After|Follow Up|Report|Dispute|Accept|Decline|Tell|Give|Welcome|Introduce|Acknowledge)\s+/i, "").toLowerCase();
  return [
    { label: "Professional", text: `Hello [name],\n\nI am writing regarding ${subject}. I would like to ${topic.context}. Please let me know the best next step and whether you need any additional information from me.\n\nThank you for your time.` },
    { label: "Short", text: `Hello [name], I am following up regarding ${subject}. Please let me know the next step when convenient. Thank you.` },
    { label: "Warm", text: `Hi [name],\n\nThank you for your time. I wanted to reach out regarding ${subject} and ${topic.context}. I appreciate your help and look forward to hearing from you.` },
    { label: "Direct", text: `Hello [name],\n\nRegarding ${subject}, please confirm [specific action/date/detail] by [date]. This will help me proceed with the next step. Thank you.` },
  ];
}

export const scaleReplies: ReplyItem[] = [...topics, ...additionalTopics].map((topic) => ({
  ...topic,
  description: `Ready-to-copy messages to ${topic.context}.`,
  variants: variantsFor(topic),
}));
